import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'dart:io' show Platform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Getting API key from environment variables
  static String get _apiKey {
    try {
      return const String.fromEnvironment('FIREBASE_API_KEY');
    } catch (e) {
      // If not available via buildtime env, try runtime env
      return Platform.environment['FIREBASE_API_KEY'] ?? 'YOUR-API-KEY';
    }
  }

  // For real Firebase configuration, these values should be generated by FlutterFire CLI
  // and the API key should be securely stored and accessed
  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _apiKey,
        appId: '1:123456789012:web:abc123def456',
        messagingSenderId: '123456789012',
        projectId: 'fitness-tracker-app',
        authDomain: 'fitness-tracker-app.firebaseapp.com',
        storageBucket: 'fitness-tracker-app.appspot.com',
        measurementId: 'G-MEASUREMENT_ID',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _apiKey,
        appId: '1:123456789012:android:abc123def456',
        messagingSenderId: '123456789012',
        projectId: 'fitness-tracker-app',
        storageBucket: 'fitness-tracker-app.appspot.com',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _apiKey,
        appId: '1:123456789012:ios:abc123def456',
        messagingSenderId: '123456789012',
        projectId: 'fitness-tracker-app',
        storageBucket: 'fitness-tracker-app.appspot.com',
        iosClientId: 'ios-client-id.apps.googleusercontent.com',
        iosBundleId: 'com.example.fitnessTracker',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: _apiKey,
        appId: '1:123456789012:macos:abc123def456',
        messagingSenderId: '123456789012',
        projectId: 'fitness-tracker-app',
        storageBucket: 'fitness-tracker-app.appspot.com',
        iosClientId: 'macos-client-id.apps.googleusercontent.com',
        iosBundleId: 'com.example.fitnessTracker.macos',
      );
}